[project]
name = "snowflake-de25-rikard-oledal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "RIKARD OLEDAL", email = "rikardoledal@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.5",
    "dlt[parquet,snowflake]>=1.30.0",
    "ipykernel>=7.3.0",
]

[project.scripts]
snowflake-de25-rikard-oledal = "snowflake_de25_rikard_oledal:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
